import { StaticImage } from 'gatsby-plugin-image'
import * as React from 'react'
import Layout from '../components/layout'
import Seo from '../components/seo'


const Systemi = () => {
  return (
    <Layout pageTitle="Системи">
      <StaticImage
        alt="Валенсія"
        src="../images/systemi/валенсія1.jpg"
      />
      <StaticImage
        alt="Валенсія"
        src="../images/systemi/валенсія2.jpg"
      />
      <StaticImage
        alt="Валенсія"
        src="../images/systemi/валенсія3.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Велс"
        src="../images/systemi/велс1.jpg"
      />
      <StaticImage
        alt="Велс"
        src="../images/systemi/велс2.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Грес"
        src="../images/systemi/грес1.jpg"
      />
      <StaticImage
        alt="Грес"
        src="../images/systemi/грес2.jpg"
      />
      <StaticImage
        alt="Грес"
        src="../images/systemi/грес3.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Джорджія"
        src="../images/systemi/джорджія1.jpg"
      />
      <StaticImage
        alt="Джорджія"
        src="../images/systemi/джорджія2.jpg"
      />
      <StaticImage
        alt="Джорджія"
        src="../images/systemi/джорджія3.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Іріс"
        src="../images/systemi/іріс1.jpg"
      />
      <StaticImage
        alt="Іріс"
        src="../images/systemi/іріс2.jpg"
      />
      <StaticImage
        alt="Іріс"
        src="../images/systemi/іріс3.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Ламі"
        src="../images/systemi/ламі1.jpg"
      />
      <StaticImage
        alt="Ламі"
        src="../images/systemi/ламі2.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Мілан"
        src="../images/systemi/мілан.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Парма"
        src="../images/systemi/парма1.jpg"
      />
      <StaticImage
        alt="Парма"
        src="../images/systemi/парма2.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Салма"
        src="../images/systemi/салма1.jpg"
      />
      <StaticImage
        alt="Салма"
        src="../images/systemi/салма2.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Тіпс"
        src="../images/systemi/тіпс1.jpg"
      />
      <StaticImage
        alt="Тіпс"
        src="../images/systemi/тіпс2.jpg"
      />
      <StaticImage
        alt="Тіпс"
        src="../images/systemi/тіпс3.jpg"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню1.jpg"
      />
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню2.jpg"
      />
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню3.jpg"
      />
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню4.jpg"
      />
    </Layout>
  )
}

export const Head = () => <Seo title="Системи" description="Системи - різного типу меблі зібрані в одне. Дешеві, українського виробництва. Купуйте в Стрию." />


export default Systemi