import { StaticImage } from 'gatsby-plugin-image'
import * as React from 'react'
import Layout from '../components/layout'
import Seo from '../components/seo'


const Systemi = () => {
  return (
    <Layout pageTitle="Системи">
      <StaticImage
        alt="Валенсія"
        src="../images/systemi/валенсія1.JPG"
      />
      <StaticImage
        alt="Валенсія"
        src="../images/systemi/валенсія2.JPG"
      />
      <StaticImage
        alt="Валенсія"
        src="../images/systemi/валенсія3.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Велс"
        src="../images/systemi/велс1.JPG"
      />
      <StaticImage
        alt="Велс"
        src="../images/systemi/велс2.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Грес"
        src="../images/systemi/грес1.JPG"
      />
      <StaticImage
        alt="Грес"
        src="../images/systemi/грес2.JPG"
      />
      <StaticImage
        alt="Грес"
        src="../images/systemi/грес3.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Джорджія"
        src="../images/systemi/джорджія1.JPG"
      />
      <StaticImage
        alt="Джорджія"
        src="../images/systemi/джорджія2.JPG"
      />
      <StaticImage
        alt="Джорджія"
        src="../images/systemi/джорджія3.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Іріс"
        src="../images/systemi/іріс1.JPG"
      />
      <StaticImage
        alt="Іріс"
        src="../images/systemi/іріс2.JPG"
      />
      <StaticImage
        alt="Іріс"
        src="../images/systemi/іріс3.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Ламі"
        src="../images/systemi/ламі1.JPG"
      />
      <StaticImage
        alt="Ламі"
        src="../images/systemi/ламі2.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Мілан"
        src="../images/systemi/мілан.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Парма"
        src="../images/systemi/парма1.JPG"
      />
      <StaticImage
        alt="Парма"
        src="../images/systemi/парма2.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Салма"
        src="../images/systemi/салма1.JPG"
      />
      <StaticImage
        alt="Салма"
        src="../images/systemi/салма2.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="Тіпс"
        src="../images/systemi/тіпс1.JPG"
      />
      <StaticImage
        alt="Тіпс"
        src="../images/systemi/тіпс2.JPG"
      />
      <StaticImage
        alt="Тіпс"
        src="../images/systemi/тіпс3.JPG"
      />
      <br/>
      <hr/>
      <br/>
      <br/>
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню1.JPG"
      />
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню2.JPG"
      />
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню3.JPG"
      />
      <StaticImage
        alt="ФантазіяНЮ"
        src="../images/systemi/фантазіяню4.JPG"
      />
    </Layout>
  )
}

export const Head = () => <Seo title="Системи" description="Системи - різного типу меблі зібрані в одне. Дешеві, українського виробництва. Купуйте в Стрию." />


export default Systemi